### ISSUE TITLE
ISO code for the prefectures

### ISSUE THREAD

**Issue by martinheidegger** [benmurden/UnMeti#1]
It would be cool if the prefectures are ISO coded: https://en.wikipedia.org/wiki/ISO_3166-2:JP

**Comment by benmurden** [comment]
Would you have this in the folder names, or suggest another schema for storage?
e.g. JP-01 Hokkaido/<image>

**Comment by martinheidegger** [comment]
hmm. `/<prefecture-code>/<index>.jpg` sounds like the only logical structure I can think of but it sucks for the users. It would be sufficiently awesome if there was a .json file that included the information.

**Comment by benmurden** [comment]
I'll dump the json as well.

**Comment by martinheidegger** [comment]
Saw it & it the codes are within the prefectures.json!
